import { LEVELS, MODE, OBJECTS, createEmptyEditorLevel } from './levels.js';

const canvas=document.getElementById('game');
const ctx=canvas.getContext('2d',{alpha:false});
const $=id=>document.getElementById(id);
const ui={menu:$('menu'),settings:$('settings'),pause:$('pausePanel'),result:$('resultPanel'),editor:$('editorPanel'),pauseBtn:$('pauseBtn'),practiceBtn:$('practiceBtn'),checkpointBtn:$('checkpointBtn'),jump:$('touchJump'),touchPause:$('touchPause'),progress:$('progress'),pct:$('pct'),title:$('title')};
let W=0,H=0,DPR=1,last=0,cameraX=0,editorData=createEmptyEditorLevel(),editorType=OBJECTS.BLOCK,editorSelection=null;
const player={x:80,y:0,size:34,vy:0,rotation:0,dualY:0,onGround:true};
const state={levelIndex:0,level:LEVELS[0],mode:MODE.CUBE,gravity:1,speed:LEVELS[0].speed,mini:false,dual:false,running:false,paused:false,practice:false,checkpoints:[],checkpointIndex:-1,buttonDown:false,audio:null,audioStart:0,musicBeat:0,portalHits:new Set(),particles:[],editor:false};
const skins={cyan:['#42e8ff','#fff'],red:['#ff5577','#ffd6df'],green:['#7dff5b','#e7ffd9'],gold:['#ffd84d','#fff4b8']};
function load(k,f){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}}
function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
let prefs=load('gd_prefs',{skin:'cyan',trail:'spark'}),progress=load('gd_progress',{completed:{},best:{},attempts:0,skins:['cyan','red','green','gold']});
function resize(){DPR=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*DPR;canvas.height=H*DPR;ctx.setTransform(DPR,0,0,DPR,0,0);if(!state.running)draw()}
addEventListener('resize',resize);
const gy=()=>H-112;
const show=e=>e.classList.remove('hidden'); const hide=e=>e.classList.add('hidden');
function updateMenu(){const completed=Object.values(progress.completed||{}).filter(Boolean).length;$('menuAttempts').textContent=progress.attempts||0;$('menuCompleted').textContent=completed+'/'+LEVELS.length;$('practiceModeBtn').textContent='Practice: '+(state.practice?'ON':'OFF');$('menuBest').textContent=(progress.best[state.level?.id]||0)+'%';const box=$('levelList');box.innerHTML='';LEVELS.forEach((l,i)=>{const d=document.createElement('div');d.className='levelCard';d.innerHTML=`<strong>${l.name}</strong><div class="small">${l.difficulty} · ${Math.round(l.length/100)}m · Best ${progress.best[l.id]||0}%</div><button>GIOCA</button>`;d.querySelector('button').onclick=()=>startLevel(i,state.practice);box.appendChild(d)});document.querySelectorAll('.skin').forEach(b=>b.classList.toggle('active',b.dataset.skin===prefs.skin));document.querySelectorAll('.trail').forEach(b=>b.classList.toggle('active',b.dataset.trail===prefs.trail))}
function resetPlayer(from=80){player.x=from;player.y=0;player.vy=0;player.dualY=0;player.rotation=0;player.size=state.mini?23:34;player.onGround=true;state.mode=MODE.CUBE;state.gravity=1;state.speed=state.level.speed;state.mini=false;state.dual=false;state.portalHits=new Set();state.checkpoints=[];state.checkpointIndex=-1;cameraX=0}
function pauseControls(on){ui.pauseBtn.style.display=on?'block':'none';ui.practiceBtn.style.display=on?'block':'none';ui.checkpointBtn.style.display=on&&state.practice?'block':'none';ui.jump.style.display=on?'block':'none';ui.touchPause.style.display=on?'block':'none'}
function startLevel(i=state.levelIndex,practice=state.practice){state.levelIndex=i;state.level=LEVELS[i];state.practice=practice;state.running=false;state.paused=false;resetPlayer();progress.attempts=(progress.attempts||0)+1;save('gd_progress',progress);hide(ui.menu);hide(ui.settings);hide(ui.pause);hide(ui.result);pauseControls(true);ui.title.textContent=`${state.level.name} · ${state.level.difficulty}`;state.running=true;startAudio();last=performance.now();requestAnimationFrame(loop)}
function startCustom(){state.level=editorData;state.levelIndex=-1;state.practice=false;state.editor=false;hide(ui.editor);resetPlayer(80);state.speed=editorData.speed;state.running=true;pauseControls(true);last=performance.now();requestAnimationFrame(loop)}
function backMenu(){stopAudio();state.running=false;state.paused=false;pauseControls(false);hide(ui.pause);hide(ui.result);hide(ui.settings);hide(ui.editor);show(ui.menu);updateMenu();draw()}
function pauseGame(){if(!state.running)return;state.paused=true;stopAudio();$('pauseInfo').textContent=`${state.level.name} · ${Math.floor(progressNow()*100)}%`;show(ui.pause);draw()}
function resume(){if(!state.running)return;state.paused=false;hide(ui.pause);startAudio();last=performance.now();requestAnimationFrame(loop)}
function restart(){if(state.practice&&state.checkpointIndex>=0)startLevelAtCheckpoint(state.checkpoints[state.checkpointIndex]);else startLevel(state.levelIndex,state.practice)}
function restartInitial(){startLevel(state.levelIndex,state.practice)}
function startLevelAtCheckpoint(x){hide(ui.result);hide(ui.pause);resetPlayer(x);state.running=true;startAudio();last=performance.now();requestAnimationFrame(loop)}
function progressNow(){return Math.max(0,Math.min(1,player.x/(state.level.length||1)))}
function inputDown(){if(!state.running||state.paused||state.editor)return;state.buttonDown=true;if(state.mode===MODE.BALL)player.vy=-state.gravity*480;else if(state.mode===MODE.WAVE)player.vy=-state.gravity*430;else player.vy=-state.gravity*(state.mode===MODE.SHIP?560:650)}
function inputUp(){state.buttonDown=false}
function processObjects(){const before=player.x,after=player.x+state.speed*.024;for(const o of state.level.objects){if(o.x<before-70||o.x>after+70)continue;const key=o.type+'@'+o.x;if(state.portalHits.has(key))continue;switch(o.type){case OBJECTS.MODE_PORTAL:state.mode=o.mode||MODE.CUBE;state.portalHits.add(key);tone(700,.045);break;case OBJECTS.GRAVITY_PORTAL:state.gravity*=-1;player.vy=0;state.portalHits.add(key);tone(520,.05);break;case OBJECTS.SPEED_PORTAL:state.speed=o.speed||state.speed;state.portalHits.add(key);tone(820,.04);break;case OBJECTS.MINI_PORTAL:state.mini=!state.mini;player.size=state.mini?23:34;state.portalHits.add(key);break;case OBJECTS.DUAL_PORTAL:state.dual=!state.dual;player.dualY=player.y;state.portalHits.add(key);break;case OBJECTS.PAD:if(Math.abs(player.x-o.x)<o.w+20)player.vy=-state.gravity*760;break;case OBJECTS.RING:if(state.buttonDown&&Math.abs(player.x-o.x)<35&&Math.abs(player.y-(o.y||110))<55)player.vy=-state.gravity*650;break;case OBJECTS.GRAVITY_RING:if(state.buttonDown&&Math.abs(player.x-o.x)<35&&Math.abs(player.y-(o.y||110))<55){state.gravity*=-1;player.vy=0}break;}}}
function updatePhysics(dt){const ceiling=Math.max(120,H-150);if(state.mode===MODE.SHIP)player.vy+=(state.buttonDown?-1250:550)*state.gravity*dt;else if(state.mode===MODE.UFO)player.vy+=(state.buttonDown?-900:900)*state.gravity*dt;else if(state.mode===MODE.WAVE)player.vy=(state.buttonDown?-430:430)*state.gravity;else player.vy+=1750*state.gravity*dt;player.y-=player.vy*dt;if(state.mode===MODE.WAVE){if(player.y<0||player.y>ceiling){crash();return}}else if(state.gravity>0&&player.y<0){player.y=0;player.vy=0;player.onGround=true}else if(state.gravity<0&&player.y>ceiling){player.y=ceiling;player.vy=0;player.onGround=true}else player.onGround=false;if(state.dual){player.dualY-=player.vy*dt;player.dualY=Math.max(0,Math.min(ceiling,player.dualY))}}
function hb(y=player.y,size=player.size){return{x:player.x+5,y:y+5,w:size-10,h:size-9}}
function overlap(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function resolvePlatforms(oldY){if(player.vy<0)return;for(const o of state.level.objects){if((o.type!==OBJECTS.BLOCK&&o.type!==OBJECTS.PLATFORM)||o.x>player.x+player.size+10||o.x+o.w<player.x-10)continue;const top=o.y||0;if(oldY<=top&&player.y>=top){player.y=top;player.vy=0;player.onGround=true}}}
function collides(o,y=player.y){const p=hb(y),base=o.y||0;if(o.type===OBJECTS.SPIKE||o.type===OBJECTS.DOUBLE)return p.x<o.x+o.w-6&&p.x+p.w>o.x+6&&p.y<45;if(o.type===OBJECTS.SAW){const cx=o.x+o.w/2,cy=base+o.h/2;return Math.hypot(player.x+player.size/2-cx,y+player.size/2-cy)<o.w/2+player.size*.30}if(o.type===OBJECTS.BLOCK||o.type===OBJECTS.PLATFORM)return overlap(p,{x:o.x,y:base,w:o.w,h:o.h});return false}
function checkCollisions(){for(const o of state.level.objects){if(o.x<player.x-80||o.x>player.x+player.size+70)continue;if(collides(o)){crash();return}}if(state.dual&&state.level.objects.some(o=>o.x>=player.x-60&&o.x<=player.x+60&&collides(o,player.dualY))){crash();return}}
function createCheckpoint(){if(!state.practice||!state.running)return;state.checkpoints.push(Math.floor(player.x));tone(850,.05)}
function crash(){if(!state.running)return;state.running=false;stopAudio();const pct=Math.floor(progressNow()*100);if(state.level.id){progress.best[state.level.id]=Math.max(progress.best[state.level.id]||0,pct);save('gd_progress',progress)}if(state.practice&&state.checkpoints.length)state.checkpointIndex=state.checkpoints.length-1;$('resultTitle').textContent='CRASH!';$('resultInfo').textContent=state.practice&&state.checkpointIndex>=0?`Progressi ${pct}%. Ultimo checkpoint disponibile.`:`Progressi ${pct}%.`;show(ui.result);draw()}
function win(){state.running=false;stopAudio();if(state.level.id){progress.completed[state.level.id]=true;progress.best[state.level.id]=100;save('gd_progress',progress)}$('resultTitle').textContent='LIVELLO COMPLETATO!';$('resultInfo').textContent=`100% · ${state.level.name}`;show(ui.result);updateMenu();draw()}
function updateParticles(dt){for(const q of state.particles)q.life-=dt;state.particles=state.particles.filter(q=>q.life>0);if(prefs.trail!=='none'&&state.running)state.particles.push({x:player.x,y:player.y,life:.22})}
function update(dt){const oldY=player.y;processObjects();player.x+=state.speed*dt;updatePhysics(dt);resolvePlatforms(oldY);checkCollisions();if(state.practice&&state.running&&player.x>=800&&state.checkpoints.length===0)state.checkpoints.push(Math.floor(player.x));cameraX=Math.max(0,player.x-W*.29);const pct=progressNow();ui.progress.style.width=pct*100+'%';ui.pct.textContent=Math.floor(pct*100)+'%';if(player.x>=state.level.length)win();updateParticles(dt)}
function draw(){drawGame()}
function drawGame(){const g=gy(),bg=ctx.createLinearGradient(0,0,0,H);bg.addColorStop(0,'#07152f');bg.addColorStop(1,'#103257');ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);ctx.strokeStyle='rgba(70,220,255,.11)';for(let xx=(-cameraX*.18)%70;xx<W;xx+=70){ctx.beginPath();ctx.moveTo(xx,0);ctx.lineTo(xx,H);ctx.stroke()}for(let yy=70;yy<g;yy+=70){ctx.beginPath();ctx.moveTo(0,yy);ctx.lineTo(W,yy);ctx.stroke()}ctx.fillStyle='#07101e';ctx.fillRect(0,g,W,H-g);ctx.strokeStyle='#42e8ff';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(0,g);ctx.lineTo(W,g);ctx.stroke();for(const o of state.level.objects){const sx=o.x-cameraX;if(sx<-100||sx>W+100)continue;drawObject(o,sx,g)}for(const q of state.particles){ctx.globalAlpha=q.life/.22*.4;ctx.fillStyle=skins[prefs.skin][0];ctx.fillRect(q.x-cameraX,g-q.y,5,5)}ctx.globalAlpha=1;drawPlayer(g,player.y);if(state.dual)drawPlayer(g,player.dualY,player.size+18)}
function drawObject(o,sx,g){if(o.type===OBJECTS.SPIKE||o.type===OBJECTS.DOUBLE){const n=o.type===OBJECTS.DOUBLE?2:1;for(let i=0;i<n;i++){const xx=sx+i*40;ctx.fillStyle='#0b1019';ctx.beginPath();ctx.moveTo(xx,g);ctx.lineTo(xx+17,g-44);ctx.lineTo(xx+34,g);ctx.closePath();ctx.fill();ctx.strokeStyle='#fff';ctx.stroke()}}else if(o.type===OBJECTS.SAW){ctx.fillStyle='#111823';ctx.beginPath();ctx.arc(sx+o.w/2,g-(o.y||35)-o.h/2,o.w/2,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff';ctx.stroke()}else if(o.type===OBJECTS.BLOCK||o.type===OBJECTS.PLATFORM){ctx.fillStyle='#101722';ctx.fillRect(sx,g-(o.y||0)-o.h,o.w,o.h);ctx.strokeStyle='#fff';ctx.strokeRect(sx,g-(o.y||0)-o.h,o.w,o.h)}else if(o.type===OBJECTS.PAD){ctx.fillStyle='#ffe34d';ctx.fillRect(sx,g-13,o.w,10)}else if(o.type===OBJECTS.RING||o.type===OBJECTS.GRAVITY_RING){ctx.strokeStyle=o.type===OBJECTS.RING?'#ffe34d':'#c86cff';ctx.lineWidth=5;ctx.beginPath();ctx.arc(sx+13,g-(o.y||110),13,0,Math.PI*2);ctx.stroke()}else{ctx.fillStyle=portalColor(o.type);ctx.globalAlpha=.75;ctx.fillRect(sx,g-120,30,120);ctx.globalAlpha=1;ctx.strokeStyle='#fff';ctx.strokeRect(sx,g-120,30,120)}}
function portalColor(t){return t===OBJECTS.GRAVITY_PORTAL?'#c86cff':t===OBJECTS.SPEED_PORTAL?'#ff9d3d':t===OBJECTS.MINI_PORTAL?'#75ffdf':t===OBJECTS.DUAL_PORTAL?'#ff5bd6':'#38ddff'}
function drawPlayer(g,y,offset=0){const [primary,secondary]=skins[prefs.skin],s=player.size,px=player.x-cameraX+offset,py=g-y-s;ctx.save();ctx.translate(px+s/2,py+s/2);ctx.rotate(player.rotation);ctx.fillStyle=primary;ctx.fillRect(-s/2,-s/2,s,s);ctx.strokeStyle=secondary;ctx.lineWidth=2;ctx.strokeRect(-s/2,-s/2,s,s);ctx.fillStyle='#0b233b';ctx.fillRect(-7,-6,4,4);ctx.fillRect(3,-6,4,4);ctx.restore()}
function loop(t){if(!state.running||state.paused)return;const dt=Math.min(.024,(t-last)/1000);last=t;update(dt);if(!state.running)return;if(!player.onGround)player.rotation+=.12;draw();scheduleAudio();requestAnimationFrame(loop)}
function startAudio(){try{state.audio=state.audio||new(window.AudioContext||window.webkitAudioContext)();state.audio.resume();state.audioStart=state.audio.currentTime;state.musicBeat=0}catch{}}
function stopAudio(){state.audioStart=0}
function tone(freq,dur=.04){if(!state.audio)return;const o=state.audio.createOscillator(),g=state.audio.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.0001,state.audio.currentTime);g.gain.exponentialRampToValueAtTime(.04,state.audio.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,state.audio.currentTime+dur);o.connect(g).connect(state.audio.destination);o.start();o.stop(state.audio.currentTime+dur+.02)}
function scheduleAudio(){if(!state.audio||!state.running)return;const beat=state.level.music==='pulse'?.30:state.level.music==='calm'?.60:.45;if(state.audio.currentTime-state.audioStart>state.musicBeat){state.musicBeat+=beat;tone(state.level.music==='pulse'?180:240,.03)}}
function editorWorld(e){const r=canvas.getBoundingClientRect();return{x:Math.round((e.clientX-r.left+cameraX)/20)*20,y:Math.max(0,Math.round((gy()-(e.clientY-r.top))/20)*20)}}
function drawEditor(){const g=gy();ctx.fillStyle='#09172d';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#20466c';for(let xx=0;xx<W;xx+=50){ctx.beginPath();ctx.moveTo(xx,0);ctx.lineTo(xx,H);ctx.stroke()}for(let yy=0;yy<g;yy+=50){ctx.beginPath();ctx.moveTo(0,yy);ctx.lineTo(W,yy);ctx.stroke()}ctx.fillStyle='#07101e';ctx.fillRect(0,g,W,H-g);for(const o of editorData.objects){const sx=o.x-cameraX,sy=g-o.y-o.h;ctx.fillStyle=portalColor(o.type);ctx.globalAlpha=.7;ctx.fillRect(sx,sy,o.w,o.h);ctx.globalAlpha=1;ctx.strokeStyle=o===editorSelection?'#ffe34d':'#fff';ctx.strokeRect(sx,sy,o.w,o.h)}}
function openEditor(){state.editor=true;state.running=false;hide(ui.menu);show(ui.editor);editorData=load('gd_editor',createEmptyEditorLevel());const tools=$('editorTools');tools.innerHTML='';for(const [name,type] of Object.entries(OBJECTS)){const b=document.createElement('button');b.className='choice editorTool';b.textContent=name;b.dataset.type=type;b.onclick=()=>{editorType=type;document.querySelectorAll('.editorTool').forEach(x=>x.classList.remove('active'));b.classList.add('active')};tools.appendChild(b)}tools.firstElementChild?.classList.add('active');drawEditor()}
function editorPointer(e){if(!state.editor)return;const w=editorWorld(e);if(e.type==='pointerdown'){const found=editorData.objects.find(o=>w.x>=o.x&&w.x<=o.x+o.w&&w.y>=o.y&&w.y<=o.y+Math.max(o.h,30));if(found)editorSelection=found;else{const o={type:editorType,x:w.x,y:w.y,w:editorType===OBJECTS.BLOCK?60:36,h:editorType===OBJECTS.BLOCK?60:40};if(editorType===OBJECTS.PAD)o.h=12;if(editorType.includes('Portal'))o.h=120;editorData.objects.push(o);editorSelection=o}drawEditor()}else if(e.type==='pointermove'&&editorSelection){editorSelection.x=w.x;editorSelection.y=w.y;drawEditor()}}
canvas.addEventListener('pointerdown',e=>{e.preventDefault();if(state.editor)editorPointer(e);else inputDown()},{passive:false});canvas.addEventListener('pointermove',e=>{if(state.editor)editorPointer(e)},{passive:false});addEventListener('pointerup',inputUp);
ui.jump.addEventListener('pointerdown',e=>{e.preventDefault();inputDown()},{passive:false});ui.jump.addEventListener('pointerup',inputUp);ui.touchPause.addEventListener('click',pauseGame);
addEventListener('keydown',e=>{if(state.editor&&e.key==='Delete'&&editorSelection){editorData.objects=editorData.objects.filter(o=>o!==editorSelection);editorSelection=null;drawEditor();return}if(['Space','ArrowUp','KeyW'].includes(e.code)){e.preventDefault();inputDown()}if(e.code==='KeyR'&&state.running){e.preventDefault();restart()}if(e.code==='KeyC'&&state.practice)createCheckpoint();if(e.code==='Escape'&&state.running)pauseGame()},{passive:false});
$('play').onclick=()=>startLevel(0,state.practice);$('practiceModeBtn').onclick=()=>{state.practice=!state.practice;updateMenu()};$('editorBtn').onclick=openEditor;$('settingsBtn').onclick=()=>{hide(ui.menu);show(ui.settings);updateMenu()};$('settingsBack').onclick=()=>{hide(ui.settings);show(ui.menu)};ui.pauseBtn.onclick=pauseGame;$('resumeBtn').onclick=resume;$('restartBtn').onclick=restart;$('startBtn').onclick=restartInitial;$('checkpointBtn').onclick=createCheckpoint;$('menuBtn').onclick=backMenu;$('resultRetry').onclick=()=>state.practice&&state.checkpointIndex>=0?startLevelAtCheckpoint(state.checkpoints[state.checkpointIndex]):startLevel(state.levelIndex,state.practice);$('resultMenu').onclick=backMenu;$('editorExit').onclick=()=>{state.editor=false;hide(ui.editor);show(ui.menu);updateMenu()};$('editorSave').onclick=()=>save('gd_editor',editorData);$('editorLoad').onclick=()=>{editorData=load('gd_editor',createEmptyEditorLevel());editorSelection=null;drawEditor()};$('editorClear').onclick=()=>{editorData=createEmptyEditorLevel();editorSelection=null;drawEditor()};$('editorTest').onclick=startCustom;document.querySelectorAll('.skin').forEach(b=>b.onclick=()=>{prefs.skin=b.dataset.skin;save('gd_prefs',prefs);updateMenu()});document.querySelectorAll('.trail').forEach(b=>b.onclick=()=>{prefs.trail=b.dataset.trail;save('gd_prefs',prefs);updateMenu()});
resize();updateMenu();draw();
