import { LEVELS, MODE, OBJECTS, createEmptyEditorLevel } from './levels.js';

const canvas=document.getElementById('game');
const ctx=canvas.getContext('2d',{alpha:false});
const $=id=>document.getElementById(id);
const ui={menu:$('menu'),settings:$('settings'),pause:$('pausePanel'),result:$('resultPanel'),editor:$('editorPanel'),pauseBtn:$('pauseBtn'),practiceBtn:$('practiceModeBtn'),checkpointBtn:$('checkpointBtn'),touchJump:$('touchJump'),touchPause:$('touchPause'),progress:$('progress'),pct:$('pct'),title:$('title'),levelList:$('levelList'),menuBest:$('menuBest'),attempts:$('menuAttempts'),completed:$('menuCompleted'),resultTitle:$('resultTitle'),resultInfo:$('resultInfo'),pauseInfo:$('pauseInfo'),editorTools:$('editorTools')};
const CFG={gravity:1800,jump:670,shipGravity:1350,shipThrust:1850,ufoGravity:1750,ufoJump:620,waveSpeed:460,groundOffset:112,lookAheadRatio:.28,speedFallback:290};
const skins={cyan:['#42e8ff','#fff'],red:['#ff5577','#ffd6df'],green:['#7dff5b','#e7ffd9'],gold:['#ffd84d','#fff4b8']};
function load(k,f){try{const r=localStorage.getItem(k);return r===null?f:JSON.parse(r)}catch{return f}} function save(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
const prefs=load('gd_prefs',{skin:'cyan',trail:'spark'});const progress=load('gd_progress',{completed:{},best:{},attempts:0,skins:['cyan','red','green','gold']});
let W=0,H=0,DPR=1,rafId=0,lastTime=0,cameraX=0;
const player={x:100,y:0,size:34,vy:0,rotation:0,onGround:true,gravity:1};
const state={levelIndex:0,level:LEVELS[0],mode:MODE.CUBE,speed:LEVELS[0]?.speed||CFG.speedFallback,mini:false,dual:false,dualY:0,running:false,paused:false,practice:false,checkpointX:null,manualCheckpoints:[],triggered:new Set(),pointerDown:false,editor:false,editorData:createEmptyEditorLevel(),editorType:OBJECTS.BLOCK,editorSelection:null,editorDragging:false,audio:null,audioStart:0,nextBeat:0,particles:[]};
const gy=()=>H-CFG.groundOffset; const show=e=>e.classList.remove('hidden'); const hide=e=>e.classList.add('hidden');
function resize(){DPR=Math.min(devicePixelRatio||1,2);W=Math.max(1,innerWidth);H=Math.max(1,innerHeight);canvas.width=Math.floor(W*DPR);canvas.height=Math.floor(H*DPR);ctx.setTransform(DPR,0,0,DPR,0,0);if(!state.running)draw()} addEventListener('resize',resize,{passive:true});
function escapeHtml(v){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function updateMenu(){const done=Object.values(progress.completed||{}).filter(Boolean).length;ui.attempts.textContent=String(progress.attempts||0);ui.completed.textContent=`${done}/${LEVELS.length}`;ui.practiceBtn.textContent=`Practice: ${state.practice?'ON':'OFF'}`;ui.menuBest.textContent=`${progress.best[state.level?.id]||0}%`;ui.levelList.innerHTML='';LEVELS.forEach((l,i)=>{const d=document.createElement('div');d.className='levelCard';d.innerHTML=`<strong>${escapeHtml(l.name)}</strong><div class="small">${escapeHtml(l.difficulty)} · ${Math.round(l.length/100)}m · Best ${progress.best[l.id]||0}%</div><button type="button">GIOCA</button>`;d.querySelector('button').addEventListener('click',()=>startLevel(i,state.practice));ui.levelList.appendChild(d)});document.querySelectorAll('.skin').forEach(b=>b.classList.toggle('active',b.dataset.skin===prefs.skin));document.querySelectorAll('.trail').forEach(b=>b.classList.toggle('active',b.dataset.trail===prefs.trail))}
function playerSize(){return state.mini?24:34}
function resetRunState(startX=100,preservePractice=false){const cp=preservePractice?state.checkpointX:null;const mcp=preservePractice?[...state.manualCheckpoints]:[];player.x=startX;player.y=0;player.vy=0;player.rotation=0;player.size=playerSize();player.onGround=true;player.gravity=1;state.mode=MODE.CUBE;state.speed=state.level.speed||CFG.speedFallback;state.mini=false;state.dual=false;state.dualY=0;state.triggered=new Set();state.checkpointX=cp;state.manualCheckpoints=mcp;state.pointerDown=false;cameraX=0}
function setGameplayControls(on){ui.pauseBtn.style.display=on?'block':'none';ui.practiceBtn.style.display=on?'block':'none';ui.checkpointBtn.style.display=on&&state.practice?'block':'none';ui.touchJump.style.display=on?'block':'none';ui.touchPause.style.display=on?'block':'none'}
function sanitizeLevel(level){const s=level||createEmptyEditorLevel();return{id:s.id||'custom',name:s.name||'Il mio livello',difficulty:s.difficulty||'Custom',length:Math.max(2000,Number(s.length)||12000),speed:Math.max(120,Number(s.speed)||CFG.speedFallback),music:s.music||'beat',objects:Array.isArray(s.objects)?s.objects.filter(Boolean).map(o=>({...o,x:Math.max(0,Number(o.x)||0),y:Math.max(0,Number(o.y)||0),w:Math.max(12,Number(o.w)||36),h:Math.max(8,Number(o.h)||36)})):[]}}
function startLevel(i=state.levelIndex,practice=state.practice){if(!LEVELS[i])return;state.levelIndex=i;state.level=LEVELS[i];state.practice=!!practice;state.running=false;state.paused=false;resetRunState(100,false);progress.attempts=Number(progress.attempts||0)+1;save('gd_progress',progress);hide(ui.menu);hide(ui.settings);hide(ui.pause);hide(ui.result);hide(ui.editor);setGameplayControls(true);ui.title.textContent=`${state.level.name} · ${state.level.difficulty}`;state.running=true;startAudio();draw();cancelAnimationFrame(rafId);rafId=requestAnimationFrame(loop)}
function startCustomLevel(){const custom=sanitizeLevel(state.editorData);if(!custom.objects.length){alert('Aggiungi almeno un oggetto al livello prima di eseguire il test.');return}state.level=custom;state.levelIndex=-1;state.practice=false;state.editor=false;hide(ui.editor);resetRunState(100,false);state.speed=custom.speed||CFG.speedFallback;state.running=true;setGameplayControls(true);startAudio();draw();cancelAnimationFrame(rafId);rafId=requestAnimationFrame(loop)}
function backToMenu(){stopAudio();state.running=false;state.paused=false;state.editor=false;setGameplayControls(false);hide(ui.settings);hide(ui.pause);hide(ui.result);hide(ui.editor);show(ui.menu);updateMenu();draw()}
function pauseGame(){if(!state.running)return;state.paused=true;stopAudio();ui.pauseInfo.textContent=`${state.level.name} · ${Math.floor(progressRatio()*100)}%`;show(ui.pause);draw()}
function resumeGame(){if(!state.running)return;state.paused=false;hide(ui.pause);startAudio();lastTime=performance.now();cancelAnimationFrame(rafId);rafId=requestAnimationFrame(loop)}
function restartRun(){if(state.practice&&state.checkpointX!==null){startFromCheckpoint(state.checkpointX);return}if(state.levelIndex>=0)startLevel(state.levelIndex,state.practice);else startCustomLevel()}
function restartInitial(){if(state.levelIndex>=0)startLevel(state.levelIndex,state.practice);else startCustomLevel()}
function startFromCheckpoint(x){hide(ui.result);hide(ui.pause);resetRunState(Math.max(100,x),true);state.running=true;setGameplayControls(true);startAudio();draw();lastTime=performance.now();cancelAnimationFrame(rafId);rafId=requestAnimationFrame(loop)}
function progressRatio(){return Math.max(0,Math.min(1,player.x/Math.max(1,state.level.length||1)))}
function inputDown(){if(!state.running||state.paused||state.editor)return;state.pointerDown=true;switch(state.mode){case MODE.BALL:player.gravity*=-1;player.vy=0;break;case MODE.UFO:player.vy=-CFG.ufoJump*player.gravity;break;case MODE.CUBE:if(player.onGround){player.vy=-CFG.jump*player.gravity;player.onGround=false}break;case MODE.SHIP:case MODE.WAVE:break;default:break}}
function inputUp(){state.pointerDown=false}
function updatePlayer(dt){const ceiling=Math.max(120,gy()-70);if(state.mode===MODE.WAVE){const dir=state.pointerDown?-1:1;player.y+=dir*CFG.waveSpeed*dt*player.gravity;if(player.y<0||player.y+player.size>ceiling){crash();return}player.onGround=false;return}if(state.mode===MODE.SHIP){player.vy+=(state.pointerDown?-CFG.shipThrust:CFG.shipGravity)*player.gravity*dt;player.vy=clamp(player.vy,-760,760);player.y-=player.vy*dt}else if(state.mode===MODE.UFO){player.vy+=CFG.ufoGravity*player.gravity*dt;player.vy=clamp(player.vy,-850,850);player.y-=player.vy*dt}else{player.vy+=CFG.gravity*player.gravity*dt;player.y-=player.vy*dt}if(state.dual){const target=Math.max(0,ceiling-player.y);state.dualY+=(target-state.dualY)*Math.min(1,dt*8);state.dualY=clamp(state.dualY,0,ceiling-player.size)}if(player.gravity>0){if(player.y<=0){player.y=0;player.vy=0;player.onGround=true}else player.onGround=false}else{const top=ceiling-player.size;if(player.y>=top){player.y=top;player.vy=0;player.onGround=true}else player.onGround=false}resolvePlatforms()}
function resolvePlatforms(){if(state.mode===MODE.WAVE||state.mode===MODE.SHIP)return;const objects=state.level.objects||[];for(const o of objects){if(o.type!==OBJECTS.BLOCK&&o.type!==OBJECTS.PLATFORM)continue;const horizontal=player.x+player.size-5>o.x&&player.x+5<o.x+o.w;if(!horizontal)continue;const top=o.y+o.h;if(player.gravity>0&&player.vy>=0){const bottom=player.y;if(bottom<=top&&bottom>=top-20){player.y=top;player.vy=0;player.onGround=true}}else if(player.gravity<0&&player.vy<=0){const topPlayer=player.y+player.size;if(topPlayer>=o.y&&topPlayer<=o.y+20){player.y=o.y-player.size;player.vy=0;player.onGround=true}}}}
function processLevelObjects(){const objects=state.level.objects||[];for(const o of objects){if(o.x>player.x+player.size+30||o.x+o.w<player.x-30)continue;const key=`${o.type}:${o.x}:${o.y}`;const oneShot=[OBJECTS.MODE_PORTAL,OBJECTS.GRAVITY_PORTAL,OBJECTS.SPEED_PORTAL,OBJECTS.MINI_PORTAL,OBJECTS.DUAL_PORTAL].includes(o.type);if(oneShot&&state.triggered.has(key))continue;switch(o.type){case OBJECTS.MODE_PORTAL:state.mode=o.mode||MODE.CUBE;player.vy=0;state.triggered.add(key);tone(760);break;case OBJECTS.GRAVITY_PORTAL:player.gravity*=-1;player.vy=0;state.triggered.add(key);tone(520);break;case OBJECTS.SPEED_PORTAL:state.speed=Math.max(120,Number(o.speed)||state.speed);state.triggered.add(key);tone(920);break;case OBJECTS.MINI_PORTAL:state.mini=!state.mini;player.size=playerSize();state.triggered.add(key);break;case OBJECTS.DUAL_PORTAL:state.dual=!state.dual;state.dualY=player.y;state.triggered.add(key);break;case OBJECTS.PAD:if(state.mode!==MODE.WAVE&&Math.abs(player.x-o.x)<=o.w+10){player.vy=-760*player.gravity;player.onGround=false}break;case OBJECTS.RING:if(state.pointerDown&&Math.abs(player.x-o.x)<36&&Math.abs(player.y-o.y)<55)player.vy=-690*player.gravity;break;case OBJECTS.GRAVITY_RING:if(state.pointerDown&&Math.abs(player.x-o.x)<36&&Math.abs(player.y-o.y)<55){player.gravity*=-1;player.vy=0}break;default:break}}}
function getPlayerHitbox(y=player.y){const inset=Math.max(4,player.size*.16);return{x:player.x+inset,y:y+inset,w:player.size-inset*2,h:player.size-inset*2}}
function checkCollisions(){const objects=state.level.objects||[];const box=getPlayerHitbox();for(const o of objects){if(o.x>player.x+player.size+90||o.x+o.w<player.x-90)continue;if(isHazard(o)&&hazardHit(o,box)){crash();return}if((o.type===OBJECTS.BLOCK||o.type===OBJECTS.PLATFORM)&&solidSideHit(o,box)){crash();return}}if(state.dual){const dual=getPlayerHitbox(state.dualY);for(const o of objects)if(isHazard(o)&&hazardHit(o,dual)){crash();return}}}
function solidSideHit(o,box){const r={x:o.x,y:o.y,w:o.w,h:o.h};if(!rectsOverlap(box,r))return false;const top=o.y+o.h;const onTop=Math.abs(box.y-top)<=5||Math.abs(box.y+box.h-top)<=5;if(onTop)return false;const under=state.gravity<0&&Math.abs(box.y+box.h-o.y)<=5;return !under}
function isHazard(o){return o.type===OBJECTS.SPIKE||o.type===OBJECTS.DOUBLE||o.type===OBJECTS.SAW}
function hazardHit(o,b){if(o.type===OBJECTS.SPIKE||o.type===OBJECTS.DOUBLE){const n=o.type===OBJECTS.DOUBLE?2:1;for(let i=0;i<n;i++){if(rectsOverlap(b,{x:o.x+i*40+7,y:0,w:20,h:42}))return true}return false}const cx=o.x+o.w/2,cy=o.y+o.h/2,dx=b.x+b.w/2-cx,dy=b.y+b.h/2-cy,r=o.w/2+b.w*.42;return dx*dx+dy*dy<=r*r}
function rectsOverlap(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function crash(){if(!state.running)return;state.running=false;stopAudio();const pct=Math.floor(progressRatio()*100);if(state.level.id){progress.best[state.level.id]=Math.max(progress.best[state.level.id]||0,pct);save('gd_progress',progress)}if(state.practice){if(state.manualCheckpoints.length)state.checkpointX=state.manualCheckpoints[state.manualCheckpoints.length-1];else state.checkpointX=Math.max(100,Math.floor(player.x/1000)*1000)}ui.resultTitle.textContent='CRASH!';ui.resultInfo.textContent=state.practice?`Progressi: ${pct}% · Checkpoint: ${Math.floor((state.checkpointX/state.level.length)*100)}%`:`Progressi: ${pct}%`;show(ui.result);draw()}
function win(){if(!state.running)return;state.running=false;stopAudio();if(state.level.id){progress.completed[state.level.id]=true;progress.best[state.level.id]=100;save('gd_progress',progress)}ui.resultTitle.textContent='LIVELLO COMPLETATO!';ui.resultInfo.textContent=`100% · ${state.level.name}`;show(ui.result);updateMenu();draw()}
function createCheckpoint(){if(!state.practice||!state.running)return;const cp=Math.floor(player.x/50)*50;state.manualCheckpoints.push(cp);state.checkpointX=cp;tone(880)}
function updateParticles(dt){for(const p of state.particles)p.life-=dt;state.particles=state.particles.filter(p=>p.life>0);if(prefs.trail!=='none'&&state.running)state.particles.push({x:player.x,y:player.y+player.size/2,life:.22})}
function loop(t){if(!state.running||state.paused)return;const dt=Math.min(.024,Math.max(.001,(t-lastTime)/1000));lastTime=t;processLevelObjects();player.x+=state.speed*dt;updatePlayer(dt);if(!state.running)return;const pct=progressRatio();ui.progress.style.width=`${pct*100}%`;ui.pct.textContent=`${Math.floor(pct*100)}%`;cameraX=Math.max(0,player.x-W*CFG.lookAheadRatio);if(player.x>=state.level.length){win();return}updateParticles(dt);draw();scheduleAudio();rafId=requestAnimationFrame(loop)}
function startAudio(){try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;if(!state.audio)state.audio=new AC;if(state.audio.state==='suspended')state.audio.resume();state.audioStart=state.audio.currentTime;state.nextBeat=0}catch{}}
function stopAudio(){state.audioStart=0}
function tone(freq=440,duration=.045){if(!state.audio)return;try{const o=state.audio.createOscillator(),g=state.audio.createGain();o.frequency.value=freq;o.type='square';g.gain.setValueAtTime(.0001,state.audio.currentTime);g.gain.exponentialRampToValueAtTime(.04,state.audio.currentTime+.008);g.gain.exponentialRampToValueAtTime(.0001,state.audio.currentTime+duration);o.connect(g).connect(state.audio.destination);o.start();o.stop(state.audio.currentTime+duration+.015)}catch{}}
function scheduleAudio(){if(!state.audio||!state.running||!state.audioStart)return;const beat=state.level.music==='pulse'?.30:state.level.music==='calm'?.60:.45;const elapsed=state.audio.currentTime-state.audioStart;if(elapsed>=state.nextBeat){state.nextBeat+=beat;tone(state.level.music==='pulse'?180:240,.025)}}
function draw(){if(state.editor)drawEditor();else drawGame()}
function drawGame(){const g=gy(),bg=ctx.createLinearGradient(0,0,0,H);bg.addColorStop(0,'#07152f');bg.addColorStop(1,'#103257');ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);ctx.strokeStyle='rgba(70,220,255,.11)';for(let x=(-cameraX*.18)%70;x<W;x+=70){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=70;y<g;y+=70){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.fillStyle='#07101e';ctx.fillRect(0,g,W,H-g);ctx.strokeStyle='#42e8ff';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(0,g);ctx.lineTo(W,g);ctx.stroke();for(const o of state.level.objects||[]){const sx=o.x-cameraX;if(sx+o.w<-100||sx>W+100)continue;drawObject(o,sx,g)}drawTrail(g);drawPlayer(g,player.y);if(state.dual)drawPlayer(g,state.dualY,player.size+18)}
function drawObject(o,x,g){switch(o.type){case OBJECTS.SPIKE:case OBJECTS.DOUBLE:{const n=o.type===OBJECTS.DOUBLE?2:1;for(let i=0;i<n;i++){const sx=x+i*40;ctx.fillStyle='#0b1019';ctx.beginPath();ctx.moveTo(sx,g);ctx.lineTo(sx+17,g-42);ctx.lineTo(sx+34,g);ctx.closePath();ctx.fill();ctx.strokeStyle='#fff';ctx.stroke()}break}case OBJECTS.SAW:{const cx=x+o.w/2,cy=g-o.y-o.h/2;ctx.fillStyle='#111823';ctx.beginPath();ctx.arc(cx,cy,o.w/2,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff';ctx.stroke();break}case OBJECTS.BLOCK:case OBJECTS.PLATFORM:{const y=g-o.y-o.h;ctx.fillStyle='#101722';ctx.fillRect(x,y,o.w,o.h);ctx.strokeStyle='#fff';ctx.strokeRect(x,y,o.w,o.h);ctx.fillStyle='rgba(60,235,255,.12)';ctx.fillRect(x+2,y+2,Math.max(1,o.w-4),Math.max(1,o.h-4));break}case OBJECTS.PAD:ctx.fillStyle='#ffe34d';ctx.fillRect(x,g-o.y-12,o.w,10);ctx.strokeStyle='#fff';ctx.strokeRect(x,g-o.y-12,o.w,10);break;case OBJECTS.RING:case OBJECTS.GRAVITY_RING:ctx.strokeStyle=o.type===OBJECTS.RING?'#ffe34d':'#c86cff';ctx.lineWidth=5;ctx.beginPath();ctx.arc(x+o.w/2,g-o.y-o.h/2,o.w/2,0,Math.PI*2);ctx.stroke();break;default:ctx.fillStyle=portalColor(o.type);ctx.globalAlpha=.8;ctx.fillRect(x,g-o.y-o.h,o.w,o.h);ctx.globalAlpha=1;ctx.strokeStyle='#fff';ctx.strokeRect(x,g-o.y-o.h,o.w,o.h)}}
function drawTrail(g){if(prefs.trail==='none')return;const primary=skins[prefs.skin][0];for(const p of state.particles){ctx.globalAlpha=Math.max(0,p.life/.22)*.5;ctx.fillStyle=primary;ctx.fillRect(p.x-cameraX,g-p.y,5,5)}ctx.globalAlpha=1}
function drawPlayer(g,y,offset=0){const [primary,secondary]=skins[prefs.skin],s=player.size,px=player.x-cameraX+offset,py=g-y-s;ctx.save();ctx.translate(px+s/2,py+s/2);ctx.rotate(player.rotation);if(state.mode===MODE.WAVE){ctx.fillStyle=primary;ctx.beginPath();ctx.moveTo(-s/2,s/2);ctx.lineTo(s/2,0);ctx.lineTo(-s/2,-s/2);ctx.closePath();ctx.fill()}else{ctx.fillStyle=primary;ctx.fillRect(-s/2,-s/2,s,s)}ctx.strokeStyle=secondary;ctx.lineWidth=2;ctx.strokeRect(-s/2,-s/2,s,s);ctx.fillStyle='#0b233b';ctx.fillRect(-7,-6,4,4);ctx.fillRect(3,-6,4,4);ctx.restore()}
function portalColor(t){return t===OBJECTS.GRAVITY_PORTAL?'#c86cff':t===OBJECTS.SPEED_PORTAL?'#ff9d3d':t===OBJECTS.MINI_PORTAL?'#75ffdf':t===OBJECTS.DUAL_PORTAL?'#ff5bd6':'#38ddff'}
function openSettings(){hide(ui.menu);show(ui.settings);updateMenu()}
function openEditor(){state.editor=true;state.running=false;hide(ui.menu);hide(ui.settings);show(ui.editor);state.editorData=sanitizeLevel(load('gd_editor',createEmptyEditorLevel()));state.editorSelection=null;state.editorDragging=false;buildEditorTools();draw()}
function buildEditorTools(){ui.editorTools.innerHTML='';for(const [name,type] of Object.entries(OBJECTS)){const b=document.createElement('button');b.type='button';b.className='choice editorTool';b.textContent=name;b.dataset.type=type;b.addEventListener('click',()=>{state.editorType=type;ui.editorTools.querySelectorAll('.editorTool').forEach(x=>x.classList.remove('active'));b.classList.add('active')});ui.editorTools.appendChild(b)}ui.editorTools.querySelector('.editorTool')?.classList.add('active')}
function editorWorldPoint(e){const r=canvas.getBoundingClientRect();return{x:Math.max(0,Math.round((e.clientX-r.left+cameraX)/20)*20),y:Math.max(0,Math.round((groundY()-(e.clientY-r.top))/20)*20)}}
function editorPointerDown(e){if(!state.editor)return;const p=editorWorldPoint(e);const existing=state.editorData.objects.find(o=>p.x>=o.x&&p.x<=o.x+o.w&&p.y>=o.y&&p.y<=o.y+Math.max(o.h,30));if(existing){state.editorSelection=existing;state.editorDragging=true;return}const o={type:state.editorType,x:p.x,y:p.y,w:state.editorType===OBJECTS.BLOCK||state.editorType===OBJECTS.PLATFORM?60:36,h:state.editorType===OBJECTS.BLOCK||state.editorType===OBJECTS.PLATFORM?60:40};if(state.editorType===OBJECTS.PAD)o.h=12;if(state.editorType.includes('Portal'))o.h=120;if(state.editorType===OBJECTS.RING||state.editorType===OBJECTS.GRAVITY_RING){o.w=28;o.h=28}state.editorData.objects.push(o);state.editorSelection=o;state.editorDragging=true}
function editorPointerMove(e){if(!state.editor||!state.editorSelection||!state.editorDragging)return;const p=editorWorldPoint(e);state.editorSelection.x=p.x;state.editorSelection.y=p.y}
function drawEditor(){const g=gy();ctx.fillStyle='#09172d';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#20466c';ctx.lineWidth=1;for(let x=0;x<W;x+=50){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<g;y+=50){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.fillStyle='#07101e';ctx.fillRect(0,g,W,H-g);for(const o of state.editorData.objects){const x=o.x-cameraX,y=g-o.y-o.h;ctx.fillStyle=portalColor(o.type);ctx.globalAlpha=.7;ctx.fillRect(x,y,o.w,o.h);ctx.globalAlpha=1;ctx.strokeStyle=o===state.editorSelection?'#ffe34d':'#fff';ctx.lineWidth=o===state.editorSelection?3:1;ctx.strokeRect(x,y,o.w,o.h)}}
function saveEditor(){const data=sanitizeLevel(state.editorData);data.length=Math.max(data.length,...data.objects.map(o=>o.x+o.w));state.editorData=data;save('gd_editor',data)}
function clearEditor(){state.editorData=createEmptyEditorLevel();state.editorSelection=null;state.editorDragging=false;draw()}
canvas.addEventListener('pointerdown',e=>{e.preventDefault();if(state.editor){editorPointerDown(e);draw();return}inputDown()},{passive:false});canvas.addEventListener('pointermove',e=>{if(!state.editor)return;e.preventDefault();editorPointerMove(e);draw()},{passive:false});
addEventListener('pointerup',()=>{inputUp();if(state.editor)state.editorDragging=false},{passive:true});addEventListener('pointercancel',()=>{inputUp();if(state.editor)state.editorDragging=false},{passive:true});
ui.touchJump.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();inputDown()},{passive:false});ui.touchJump.addEventListener('pointerup',inputUp,{passive:true});ui.touchJump.addEventListener('pointercancel',inputUp,{passive:true});ui.touchPause.addEventListener('click',pauseGame);
addEventListener('keydown',e=>{if(state.editor&&e.key==='Delete'){if(state.editorSelection){state.editorData.objects=state.editorData.objects.filter(o=>o!==state.editorSelection);state.editorSelection=null;draw()}return}if(['Space','ArrowUp','KeyW'].includes(e.code)){e.preventDefault();inputDown()}if(e.code==='KeyR'&&state.running){e.preventDefault();restartRun()}if(e.code==='KeyC'&&state.practice&&state.running){e.preventDefault();createCheckpoint()}if(e.code==='Escape'&&state.running){e.preventDefault();pauseGame()}},{passive:false});addEventListener('keyup',e=>{if(['Space','ArrowUp','KeyW'].includes(e.code))inputUp()},{passive:true});addEventListener('blur',inputUp);document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.running&&!state.paused)pauseGame()});
$('play').addEventListener('click',()=>startLevel(0,state.practice));ui.practiceBtn.addEventListener('click',()=>{state.practice=!state.practice;updateMenu()});$('editorBtn').addEventListener('click',openEditor);$('settingsBtn').addEventListener('click',openSettings);$('settingsBack').addEventListener('click',()=>{hide(ui.settings);show(ui.menu)});ui.pauseBtn.addEventListener('click',pauseGame);$('resumeBtn').addEventListener('click',resumeGame);$('restartBtn').addEventListener('click',restartRun);$('startBtn').addEventListener('click',restartInitial);$('checkpointBtn').addEventListener('click',createCheckpoint);$('menuBtn').addEventListener('click',backToMenu);$('resultRetry').addEventListener('click',restartRun);$('resultMenu').addEventListener('click',backToMenu);$('editorExit').addEventListener('click',()=>{state.editor=false;hide(ui.editor);show(ui.menu);updateMenu();draw()});$('editorSave').addEventListener('click',saveEditor);$('editorLoad').addEventListener('click',()=>{state.editorData=sanitizeLevel(load('gd_editor',createEmptyEditorLevel()));state.editorSelection=null;draw()});$('editorClear').addEventListener('click',clearEditor);$('editorTest').addEventListener('click',startCustomLevel);document.querySelectorAll('.skin').forEach(b=>b.addEventListener('click',()=>{prefs.skin=b.dataset.skin;save('gd_prefs',prefs);updateMenu();draw()}));document.querySelectorAll('.trail').forEach(b=>b.addEventListener('click',()=>{prefs.trail=b.dataset.trail;save('gd_prefs',prefs);updateMenu();draw()}));
for(const n of ['gesturestart','gesturechange','gestureend','contextmenu'])document.addEventListener(n,e=>e.preventDefault(),{passive:false});
resize();updateMenu();draw();
function clamp(v,min,max){return Math.max(min,Math.min(max,v))}
