export const MODE={CUBE:'cube',SHIP:'ship',BALL:'ball',UFO:'ufo',WAVE:'wave'};
export const OBJECTS={SPIKE:'spike',DOUBLE:'doubleSpike',BLOCK:'block',PLATFORM:'platform',SAW:'saw',PAD:'pad',RING:'ring',GRAVITY_RING:'gravityRing',MODE_PORTAL:'modePortal',GRAVITY_PORTAL:'gravityPortal',SPEED_PORTAL:'speedPortal',MINI_PORTAL:'miniPortal',DUAL_PORTAL:'dualPortal'};
export const WORLD={H:320,FLOOR:0,CEILING:288,WARNING:248,SPEED_MIN:120,SPEED_MAX:900,GRAVITY:1800,CUBE_JUMP:650,UFO_IMPULSE:600,WAVE_SPEED:430,SHIP_UP_ACCEL:900,SHIP_DOWN_ACCEL:1050,SHIP_MAX_UP:330,SHIP_MAX_DOWN:420,PORTAL_GRACE:.12};
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const overlap=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
const hitbox=p=>({x:p.x+4,y:p.y+4,w:Math.max(2,p.size-8),h:Math.max(2,p.size-8)});
const makePlayer=id=>({id,x:100,y:0,size:34,vy:0,gravity:1,mode:MODE.CUBE,onGround:true,alive:true,hold:false,inputBuffer:0,mini:false,rotation:0,portalGrace:0});

export class GameEngine{
 constructor(level){this.level=level;this.resetState()}
 resetState(){this.players=[makePlayer(0)];this.speed=clamp(Number(this.level.speed)||285,WORLD.SPEED_MIN,WORLD.SPEED_MAX);this.running=false;this.completed=false;this.crashed=false;this.checkpoint=null;this.checkpoints=[];this.triggered=new Set();this.actions=new Set()}
 reset(startX=100,preserve=false){const cp=preserve?this.checkpoint:null;const cps=preserve?[...this.checkpoints]:[];this.players=[makePlayer(0)];const p=this.players[0];p.x=Math.max(100,startX);p.y=WORLD.FLOOR;p.vy=0;p.gravity=1;p.mode=MODE.CUBE;p.onGround=true;p.alive=true;p.hold=false;p.inputBuffer=0;p.mini=false;p.size=34;p.portalGrace=0;this.speed=clamp(Number(this.level.speed)||285,WORLD.SPEED_MIN,WORLD.SPEED_MAX);this.running=true;this.completed=false;this.crashed=false;this.triggered.clear();this.actions.clear();this.checkpoint=cp;this.checkpoints=cps}
 inputDown(){if(!this.running)return;for(const p of this.players){p.inputBuffer=.10;if(p.mode===MODE.CUBE){if(p.onGround){p.vy=WORLD.CUBE_JUMP*p.gravity;p.onGround=false;p.inputBuffer=0}}else if(p.mode===MODE.BALL){if(p.onGround){p.gravity*=-1;p.vy=0;p.onGround=false;p.inputBuffer=0}}else if(p.mode===MODE.UFO){p.vy=WORLD.UFO_IMPULSE*p.gravity;p.onGround=false;p.inputBuffer=0}else if(p.mode===MODE.SHIP||p.mode===MODE.WAVE){p.hold=true}}}
 release(){for(const p of this.players)p.hold=false}
 step(dt){if(!this.running)return;const prevX=this.players[0]?.x??100;for(const p of this.players){if(!p.alive)continue;p.inputBuffer=Math.max(0,p.inputBuffer-dt);p.portalGrace=Math.max(0,p.portalGrace-dt);p.x+=this.speed*dt}this.processPortals(prevX,this.players[0]?.x??prevX);for(const p of this.players){if(!p.alive)continue;this.updateVertical(p,dt);if(!this.resolveWorldAndSolids(p)||!this.checkHazards(p)){this.crash();return}this.processPadsAndRings(p)}this.syncDual();if(this.players[0].x>=this.level.length){this.running=false;this.completed=true}}
 updateVertical(p,dt){if(p.portalGrace>0&&(p.mode===MODE.SHIP||p.mode===MODE.UFO||p.mode===MODE.WAVE)){p.onGround=false;return}if(p.mode===MODE.WAVE){p.y+=(p.hold?1:-1)*p.gravity*WORLD.WAVE_SPEED*(p.mini?2:1)*dt;p.onGround=false;return}if(p.mode===MODE.SHIP){const desired=p.hold?p.gravity*WORLD.SHIP_MAX_UP:p.gravity*-WORLD.SHIP_MAX_DOWN;const rate=p.hold?WORLD.SHIP_UP_ACCEL:WORLD.SHIP_DOWN_ACCEL;const maxChange=rate*dt;const delta=desired-p.vy;p.vy=clamp(p.vy+clamp(delta,-maxChange,maxChange),-WORLD.SHIP_MAX_DOWN,WORLD.SHIP_MAX_UP);p.y+=p.vy*dt;return}const accel=p.mode===MODE.UFO?-p.gravity*1450:-p.gravity*WORLD.GRAVITY;p.vy=clamp(p.vy+accel*dt,-900,900);p.y+=p.vy*dt}
 resolveWorldAndSolids(p){if(p.mode===MODE.SHIP||p.mode===MODE.UFO||p.mode===MODE.WAVE)return p.y>=WORLD.FLOOR&&p.y+p.size<=WORLD.CEILING;const b=hitbox(p);let landed=false;for(const o of this.solids()){if(b.x+b.w<=o.x||b.x>=o.x+o.w)continue;if(p.gravity>0){const top=o.y+o.h;if(p.y<=top&&p.y>=top-p.size-5&&p.vy<=0){p.y=top;p.vy=0;p.onGround=true;landed=true}}else{const bottom=o.y;if(p.y+p.size>=bottom&&p.y+p.size<=bottom+p.size+5&&p.vy>=0){p.y=bottom-p.size;p.vy=0;p.onGround=true;landed=true}}}if(p.gravity>0&&p.y<=WORLD.FLOOR){p.y=WORLD.FLOOR;p.vy=0;p.onGround=true;landed=true}if(p.gravity<0&&p.y+p.size>=WORLD.CEILING){p.y=WORLD.CEILING-p.size;p.vy=0;p.onGround=true;landed=true}if(landed)return true;if(p.y<WORLD.FLOOR||p.y+p.size>WORLD.CEILING)return false;for(const o of this.solids()){if(!overlap(hitbox(p),o))continue;const hb=hitbox(p);const topContact=p.gravity>0&&Math.abs(hb.y-(o.y+o.h))<5;const bottomContact=p.gravity<0&&Math.abs(hb.y+hb.h-o.y)<5;if(!topContact&&!bottomContact)return false}return true}
 solids(){return(this.level.objects||[]).filter(o=>o.type===OBJECTS.BLOCK||o.type===OBJECTS.PLATFORM)}
 hazards(){return(this.level.objects||[]).filter(o=>o.type===OBJECTS.SPIKE||o.type===OBJECTS.DOUBLE||o.type===OBJECTS.SAW)}
 checkHazards(p){if(p.portalGrace>0)return true;const b=hitbox(p);for(const o of this.hazards()){if(o.type===OBJECTS.SAW){const cx=o.x+o.w/2,cy=o.y+o.h/2,dx=b.x+b.w/2-cx,dy=b.y+b.h/2-cy,r=o.w/2+b.w*.45;if(dx*dx+dy*dy<r*r)return false}else{const n=o.type===OBJECTS.DOUBLE?2:1;for(let i=0;i<n;i++){const h={x:o.x+i*40+5,y:o.y,w:Math.min(30,o.w-8),h:o.h};if(overlap(b,h))return false}}}return true}
 processPortals(prevX,currentX){for(const o of this.level.objects||[]){if(![OBJECTS.MODE_PORTAL,OBJECTS.GRAVITY_PORTAL,OBJECTS.SPEED_PORTAL,OBJECTS.MINI_PORTAL,OBJECTS.DUAL_PORTAL].includes(o.type))continue;if(!(prevX<o.x&&currentX>=o.x))continue;const key=`${o.type}:${o.x}:${o.y}`;if(this.triggered.has(key))continue;this.triggered.add(key);if(o.type===OBJECTS.MODE_PORTAL){for(const p of this.players){p.mode=o.mode||MODE.CUBE;p.vy=0;p.onGround=false;p.inputBuffer=0;p.hold=false;p.portalGrace=WORLD.PORTAL_GRACE;p.size=p.mini?24:34;if(p.mode===MODE.SHIP)p.y=145;else if(p.mode===MODE.UFO)p.y=140;else if(p.mode===MODE.WAVE)p.y=145;else p.y=clamp(p.y,WORLD.FLOOR,WORLD.CEILING-p.size)}}else if(o.type===OBJECTS.GRAVITY_PORTAL){for(const p of this.players){p.gravity*=-1;p.vy=0;p.onGround=false;p.portalGrace=.08}}else if(o.type===OBJECTS.SPEED_PORTAL){this.speed=clamp(Number(o.speed)||this.speed,WORLD.SPEED_MIN,WORLD.SPEED_MAX)}else if(o.type===OBJECTS.MINI_PORTAL){for(const p of this.players){p.mini=!p.mini;p.size=p.mini?24:34;p.y=clamp(p.y,WORLD.FLOOR,WORLD.CEILING-p.size);p.portalGrace=.08}}else if(o.type===OBJECTS.DUAL_PORTAL)this.toggleDual()}}
 processPadsAndRings(p){if(p.mode===MODE.WAVE||p.portalGrace>0)return;const b=hitbox(p);for(const o of this.level.objects||[]){if(!overlap(b,o))continue;const key=`${o.type}:${o.x}:${o.y}:${p.id}`;if(this.actions.has(key))continue;if(o.type===OBJECTS.PAD){const touching=p.onGround;const descending=p.gravity>0?p.vy<0:p.vy>0;if(touching||descending){p.vy=p.gravity*760;p.onGround=false;this.actions.add(key)}}else if((o.type===OBJECTS.RING||o.type===OBJECTS.GRAVITY_RING)&&p.inputBuffer>0){if(o.type===OBJECTS.RING)p.vy=p.gravity*700;else{p.gravity*=-1;p.vy=0;p.onGround=false}p.inputBuffer=0;this.actions.add(key)}}p.inputBuffer=0}
 toggleDual(){if(this.players.length===2){this.players.pop();return}const a=this.players[0],b=makePlayer(1);b.x=a.x;b.mode=a.mode;b.gravity=-a.gravity;b.size=a.size;b.mini=a.mini;b.y=clamp(WORLD.CEILING-a.y-a.size,60,WORLD.CEILING-b.size-60);b.portalGrace=.12;this.players.push(b)}
 syncDual(){if(this.players.length!==2)return;const a=this.players[0],b=this.players[1];b.x=a.x;b.mode=a.mode;b.gravity=-a.gravity;b.size=a.size;b.mini=a.mini;b.y=clamp(WORLD.CEILING-a.y-a.size,WORLD.FLOOR,WORLD.CEILING-b.size);b.portalGrace=Math.max(0,b.portalGrace-.01)}
 checkpoint(){if(!this.running)return;const x=Math.floor(this.players[0].x/100)*100;if(!this.checkpoints.includes(x))this.checkpoints.push(x);this.checkpoint=x}
 crash(){this.running=false;this.crashed=true;this.players.forEach(p=>p.alive=false)}
 getProgress(){return clamp((this.players[0].x-100)/Math.max(1,this.level.length-100),0,1)}
}
